# REQUIRED CHANGES
# Edit next line to provide your own name.
title: Jermaine Bruno | Professional Portfolio
# Edit next line, replacing 'techfolios' with your github username
url: "https://Soon-Hari.github.io"
# Edit next line so that baseurl is "" if your repo is <username>.github.io
baseurl: ""

# OPTIONAL CHANGES
## Specify the theme using Hydejack remote theme
remote_theme: hydecorp/hydejack@v9.2.1
## Specify the formatting for triple backquote code sections.
rouge-theme: github.css

# DON'T CHANGE THE FOLLOWING (unless you know what you're doing)
markdown: kramdown
kramdown:
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
strict_front_matter: true
mathjax: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
include:
  - .nojekyll
  - _data
plugins:
  - jekyll-gist
